<a href="https://colab.research.google.com/github/ompatel420/ML-Practicals/blob/main/ML_P2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **2CEIT506:Machine Learning**
---
# **Practical - 2**
## 24012011117
---
PATEL OMKUMAR VINODCHANDRA
---
5CE-I-1


Aim:
1. Understanding of Data Pre-processing for given dataset 1 using Spyder (Python)
2. Replace Missing values by below imputation strategy.

In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [3]:
dataset =pd.read_csv('/content/drive/MyDrive/ML/Dataset/dataset1.csv')
dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [4]:
dataset.shape

(10, 4)

In [5]:
dataset.describe()

,Age,Salary
count,9.000000,9.000000
mean,38.777778,63777.777778
std,7.693793,12265.579662
min,27.000000,48000.000000
25%,35.000000,54000.000000
50%,38.000000,61000.000000
75%,44.000000,72000.000000
max,50.000000,83000.000000


In [6]:
dataset.isna().sum()

,0
Country,0
Age,1
Salary,1
Purchased,0


In [7]:
dataset.head()
dataset.info()
dataset.describe()
dataset.isnull().sum()
dataset.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


(10, 4)

Mean, Median and Most Frequent

In [8]:
import numpy as np
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values=np.nan, strategy="mean")

In [9]:
si

SimpleImputer()

In [10]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [11]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [12]:
import numpy as np
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values=np.nan, strategy="median")


In [13]:
si

SimpleImputer(strategy='median')

In [14]:
x[:, 1:3] = si.fit_transform(x[:, 1:3])

In [15]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Label Encoder

3. Understanding of categorical data.

4. Replace Country Attribute for given dataset 1 by fit_transform method.

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [17]:
x[:, 0] = le.fit_transform(x[:, 0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 61000.0],
       [0, 35.0, 58000.0],
       [2, 38.0, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [18]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [19]:
x[:, 1:3] = ss.fit_transform(x[:, 1:3])
x

array([[0, 0.7697343929216671, 0.7725676677947168],
       [2, -1.6992249806006627, -1.4087998648021307],
       [1, -1.2635262676261338, -0.8634579816529188],
       [2, -0.10166303302739046, -0.22722578464550494],
       [1, 0.1888027756222954, -0.22722578464550494],
       [0, -0.5373617460019192, -0.4998967262201109],
       [2, -0.10166303302739046, -1.0452386093693227],
       [0, 1.3506660102210388, 1.4087998648021307],
       [1, 1.6411318188707247, 1.7723611202349385],
       [0, -0.2468959373522334, 0.3181160985037069]], dtype=object)

In [20]:
print(x)
print(y)

[[0 0.7697343929216671 0.7725676677947168]
 [2 -1.6992249806006627 -1.4087998648021307]
 [1 -1.2635262676261338 -0.8634579816529188]
 [2 -0.10166303302739046 -0.22722578464550494]
 [1 0.1888027756222954 -0.22722578464550494]
 [0 -0.5373617460019192 -0.4998967262201109]
 [2 -0.10166303302739046 -1.0452386093693227]
 [0 1.3506660102210388 1.4087998648021307]
 [1 1.6411318188707247 1.7723611202349385]
 [0 -0.2468959373522334 0.3181160985037069]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [21]:
dataset2 = pd.read_csv('/content/drive/MyDrive/ML/Dataset/dataset2.csv')
dataset2

,Outlook,Outlook0,Outlook1
0,Sunny,1,Sunny
1,Sunny,2,Sunny
2,Overcast,3,Overcast
3,Rain,4,Rain
4,Rain,5,Rain
5,Rain,2,Rain
6,Overcast,3,Overcast
7,Sunny,1,Sunny
8,Sunny,2,Sunny
9,Rain,3,Rain


Double-click (or enter) to edit

In [22]:
x = dataset2.iloc[:, :].values
print(x)

[['Sunny' 1 'Sunny']
 ['Sunny' 2 'Sunny']
 ['Overcast' 3 'Overcast']
 ['Rain' 4 'Rain']
 ['Rain' 5 'Rain']
 ['Rain' 2 'Rain']
 ['Overcast' 3 'Overcast']
 ['Sunny' 1 'Sunny']
 ['Sunny' 2 'Sunny']
 ['Rain' 3 'Rain']
 ['Sunny' 4 'Sunny']
 ['Overcast' 2 'Overcast']
 ['Overcast' 1 'Overcast']
 ['Rain' 3 'Rain']]


In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [24]:
x[:, 0] = le.fit_transform(x[:, 0])
print(x)

[[2 1 'Sunny']
 [2 2 'Sunny']
 [0 3 'Overcast']
 [1 4 'Rain']
 [1 5 'Rain']
 [1 2 'Rain']
 [0 3 'Overcast']
 [2 1 'Sunny']
 [2 2 'Sunny']
 [1 3 'Rain']
 [2 4 'Sunny']
 [0 2 'Overcast']
 [0 1 'Overcast']
 [1 3 'Rain']]


OneHotEncoder

5. Replace categorical and numerical Attributes for given dataset 2 by OneHotEncoder Class.

In [25]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("column0", OneHotEncoder(), [0])], remainder="passthrough")

In [26]:
x = ct.fit_transform(x)
print(x)


[[0.0 0.0 1.0 1 'Sunny']
 [0.0 0.0 1.0 2 'Sunny']
 [1.0 0.0 0.0 3 'Overcast']
 [0.0 1.0 0.0 4 'Rain']
 [0.0 1.0 0.0 5 'Rain']
 [0.0 1.0 0.0 2 'Rain']
 [1.0 0.0 0.0 3 'Overcast']
 [0.0 0.0 1.0 1 'Sunny']
 [0.0 0.0 1.0 2 'Sunny']
 [0.0 1.0 0.0 3 'Rain']
 [0.0 0.0 1.0 4 'Sunny']
 [1.0 0.0 0.0 2 'Overcast']
 [1.0 0.0 0.0 1 'Overcast']
 [0.0 1.0 0.0 3 'Rain']]


In [27]:
x = x[:, 1:]
print(x)

[[0.0 1.0 1 'Sunny']
 [0.0 1.0 2 'Sunny']
 [0.0 0.0 3 'Overcast']
 [1.0 0.0 4 'Rain']
 [1.0 0.0 5 'Rain']
 [1.0 0.0 2 'Rain']
 [0.0 0.0 3 'Overcast']
 [0.0 1.0 1 'Sunny']
 [0.0 1.0 2 'Sunny']
 [1.0 0.0 3 'Rain']
 [0.0 1.0 4 'Sunny']
 [0.0 0.0 2 'Overcast']
 [0.0 0.0 1 'Overcast']
 [1.0 0.0 3 'Rain']]


In [28]:
ct = ColumnTransformer([("column3", OneHotEncoder(), [3])], remainder="passthrough")
x = ct.fit_transform(x)
print(x)

[[0.0 0.0 1.0 0.0 1.0 1]
 [0.0 0.0 1.0 0.0 1.0 2]
 [1.0 0.0 0.0 0.0 0.0 3]
 [0.0 1.0 0.0 1.0 0.0 4]
 [0.0 1.0 0.0 1.0 0.0 5]
 [0.0 1.0 0.0 1.0 0.0 2]
 [1.0 0.0 0.0 0.0 0.0 3]
 [0.0 0.0 1.0 0.0 1.0 1]
 [0.0 0.0 1.0 0.0 1.0 2]
 [0.0 1.0 0.0 1.0 0.0 3]
 [0.0 0.0 1.0 0.0 1.0 4]
 [1.0 0.0 0.0 0.0 0.0 2]
 [1.0 0.0 0.0 0.0 0.0 1]
 [0.0 1.0 0.0 1.0 0.0 3]]


In [29]:
dataset3 = pd.get_dummies(dataset2, dtype=int)
print(dataset3)

    Outlook0  Outlook_Overcast  Outlook_Rain  Outlook_Sunny  \
0          1                 0             0              1   
1          2                 0             0              1   
2          3                 1             0              0   
3          4                 0             1              0   
4          5                 0             1              0   
5          2                 0             1              0   
6          3                 1             0              0   
7          1                 0             0              1   
8          2                 0             0              1   
9          3                 0             1              0   
10         4                 0             0              1   
11         2                 1             0              0   
12         1                 1             0              0   
13         3                 0             1              0   

    Outlook1_Overcast  Outlook1_Rain  Outlook1_Sunny  

In [30]:
dataset4 = pd.get_dummies(dataset2, dtype=int, drop_first=True)
print(dataset4)

    Outlook0  Outlook_Rain  Outlook_Sunny  Outlook1_Rain  Outlook1_Sunny
0          1             0              1              0               1
1          2             0              1              0               1
2          3             0              0              0               0
3          4             1              0              1               0
4          5             1              0              1               0
5          2             1              0              1               0
6          3             0              0              0               0
7          1             0              1              0               1
8          2             0              1              0               1
9          3             1              0              1               0
10         4             0              1              0               1
11         2             0              0              0               0
12         1             0              0          